version: '3'

services: 
    app:
        build: ./.docker/service
        volumes:
            - ./:/var/www

    app-nginx:
        build: ./.docker/nginx
        restart: always
        ports: 
            - "8002:80"
        volumes:
            - "./:/var/www"
        depends_on: 
            - app