version: '3'

services: 
    projectapp:
        build: ./.docker/service
        volumes:
            - ./unit_4/:/var/www

    projectapp-nginx:
        build: ./.docker/nginx
        restart: always
        ports: 
            - "8002:80"
        volumes:
            - "./unit_4/:/var/www"
        depends_on: 
            - projectapp